name: Update Submodules

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '10 0 * * *'  # Execute at midnight every day

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Make sure to check out the sub-module

      - name: Update submodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive

      - name: Check if changes were made and commit if found
        id: check_and_push_changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes were made."
          else
            echo "Changes found in a submodule." # This can be further abstracted to give specific submod name, possibly.
            git config --global user.email "cloudscythelabs@gmail.com"
            git config --global user.name "Cloud Scythe Labs"
            git add .
            git commit -m 'Update submodule'
            git push
          fi
